# Generated by Django 2.1.1 on 2018-09-01 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('plataforma', models.CharField(choices=[('Não identificado', 'Não identificado'), ('TV', 'TV'), ('Mobile', 'Mobile'), ('Site', 'Site'), ('Game', 'Game'), ('Back End', 'Back End'), ('Todos', 'Todos')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=250, null=True)),
                ('provedores', models.CharField(blank=True, default='Não identificado', max_length=250, null=True)),
                ('datainicio', models.DateTimeField(default=datetime.datetime(2018, 9, 1, 10, 18, 51, 334693), verbose_name='Data de Início')),
                ('datafim', models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 1, 10, 18, 51, 334693), null=True, verbose_name='Data de Fim')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
