# Generated by Django 2.1.1 on 2018-09-01 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djanguinhobasico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='datafim',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 1, 10, 25, 32, 979396), null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='datainicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 10, 25, 32, 979396), verbose_name='Data de Início'),
        ),
    ]
